addons:
    apt:
        packages:
            - ack-grep
            - asciidoc
            - build-essential
            - cmake
            - cpanminus
            - dbtoepub
            - docbook-defguide
            - docbook-xsl
            - docbook-xsl-ns
            - fop
            - fortune-mod
            - graphicsmagick
            - hunspell
            - inkscape
            - myspell-en-gb
            - libdb5.3-dev
            - libgd-dev
            - libhunspell-dev
            - libncurses-dev
            - libpcre3-dev
            - libperl-dev
            - libxml2-dev
            - mercurial
            - myspell-en-gb
            - lynx
            - optipng
            - perl
            - python3
            - python3-setuptools
            - python3-pip
            - silversearcher-ag
            - strip-nondeterminism
            - tidy
            - valgrind
            - wml
            - xsltproc
            - xz-utils
            - zip
dist: xenial
perl:
    - '5.26'
matrix:
    fast_finish: true
os: linux
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - gem install asciidoctor
    - cpanm -n App::XML::DocBook::Docmake Code::TidyAll::Plugin::TestCount HTML::T5 MooX MooX::late Perl::Critic Perl::Tidy Test::HTML::Tidy::Recursive Test::TrailingSpace Test::Code::TidyAll
script:
    - bash -x .travis-run-test.bash
